create table public.hotels (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  description text,
  logo_url text,
  theme jsonb default '{}'::jsonb
);

-- Enable RLS
alter table public.hotels enable row level security;

-- Create policies
create policy "Users can view their own hotels"
  on public.hotels for select
  using (auth.uid() = user_id);

create policy "Users can insert their own hotels"
  on public.hotels for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own hotels"
  on public.hotels for update
  using (auth.uid() = user_id);

create policy "Users can delete their own hotels"
  on public.hotels for delete
  using (auth.uid() = user_id);

-- Create indexes
create index hotels_user_id_idx on public.hotels(user_id);
create index hotels_slug_idx on public.hotels(slug); 